const cards = [
	null,
	{
		"name": "Mohan Lal",
		"region": 'Kabul',
		"suit": 'Intelligence',
		"rank": 3,
		"spies": 3,
		"move": 3,
		"prize": 'Russian',
		"number": 1
	},
	{
		"name": "Jan-Fishan Khan",
		"region": 'Kabul',
		"suit": 'Intelligence',
		"rank": 2,
		"armies": 1,
		"spies": 2,
		"climate": 'Military',
		"move": 2,
		"battle": 2,
		"prize": 'Russian',
		"number": 2
	},
	{
		"name": "Prince Akbar Khan",
		"region": 'Kabul',
		"suit": 'Intelligence',
		"rank": 2,
		"armies": 1,
		"spies": 2,
		"climate": 'Military',
		"battle": 2,
		"patriot": 'Afghan',
		"number": 3
	},
	{
		"name": "Charles Stoddart",
		"region": 'Kabul',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"gift": 1,
		"move": 1,
		"prize": 'Afghan',
		"number": 4
	},
	{
		"name": "Shah Shujah Durrani",
		"region": 'Kabul',
		"suit": 'Political',
		"rank": 1,
		"tribes": 1,
		"build": 1,
		"prize": 'Afghan',
		"number": 5
	},
	{
		"name": "Aminullah Khan Logari",
		"region": 'Kabul',
		"suit": 'Political',
		"rank": 1,
		"armies": 1,
		"tribes": 1,
		"spies": 1,
		"build": 1,
		"move": 1,
		"patriot": 'Afghan',
		"number": 6
	},
	{
		"name": "Dost Mohammad",
		"region": 'Kabul',
		"suit": 'Political',
		"rank": 2,
		"armies": 1,
		"tribes": 2,
		"spies": 1,
		"number": 7
	},
	{
		"name": "Kabul Bazaar",
		"region": 'Kabul',
		"suit": 'Economic',
		"rank": 2,
		"roads": 2,
		"spies": 1,
		"climate": 'Political',
		"tax": 2,
		"number": 8
	},
	{
		"name": "Afghan Handicrafts",
		"region": 'Kabul',
		"suit": 'Economic',
		"rank": 1,
		"roads": 1,
		"tax": 1,
		"move": 1,
		"number": 9
	},
	{
		"name": "Balkh Arsenic Mine",
		"region": 'Kabul',
		"suit": 'Economic',
		"rank": 1,
		"roads": 1,
		"climate": 'Military',
		"build": 1,
		"betray": 1,
		"prize": 'Afghan',
		"number": 10
	},
	{
		"name": "Lapis Lazuli Mine",
		"region": 'Kabul',
		"suit": 'Economic',
		"rank": 2,
		"roads": 2,
		"tax": 2,
		"gift": 1,
		"patriot": 'Afghan',
		"number": 11
	},
	{
		"name": "City of Ghazni",
		"region": 'Kabul',
		"suit": 'Economic',
		"rank": 3,
		"armies": 1,
		"roads": 3,
		"gift": 1,
		"number": 12
	},
	{
		"name": "Ghilzai Nomads",
		"region": 'Kabul',
		"suit": 'Economic',
		"rank": 2,
		"roads": 2,
		"tax": 2,
		"move": 2,
		"prize": 'Russian',
		"number": 13
	},
	{
		"name": "Money Lenders",
		"region": 'Kabul',
		"suit": 'Economic',
		"rank": 2,
		"roads": 2,
		"leveraged": 1,
		"gift": 1,
		"build": 1,
		"number": 14
	},
	{
		"name": "Durrani Royal Guard",
		"region": 'Kabul',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"betray": 1,
		"number": 15
	},
	{
		"name": "Bala Hissar",
		"region": 'Kabul',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"tax": 1,
		"betray": 1,
		"number": 16
	},
	{
		"name": "Citadel of Ghazni",
		"region": 'Kabul',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"build": 1,
		"number": 17
	},
	{
		"name": "Harry Flashman",
		"region": 'Punjab',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"gift": 1,
		"betray": 1,
		"number": 18
	},
	{
		"name": "Eldred Pottinger",
		"region": 'Punjab',
		"suit": 'Intelligence',
		"rank": 2,
		"spies": 2,
		"climate": 'Economic',
		"move": 2,
		"betray": 1,
		"patriot": 'British',
		"prize": 'Russian',
		"number": 19
	},
	{
		"name": "Henry Rawlinson",
		"region": 'Punjab',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"climate": 'Economic',
		"gift": 1,
		"move": 1,
		"patriot": 'British',
		"prize": 'Russian',
		"number": 20
	},
	{
		"name": "Alexander Burnes",
		"region": 'Punjab',
		"suit": 'Intelligence',
		"rank": 2,
		"spies": 2,
		"move": 2,
		"prize": 'Afghan',
		"number": 21
	},
	{
		"name": "George Hayward",
		"region": 'Punjab',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"climate": 'Political',
		"gift": 1,
		"move": 1,
		"patriot": 'British',
		"prize": 'Russian',
		"number": 22
	},
	{
		"name": "Henry Pottinger",
		"region": 'Punjab',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"climate": 'Economic',
		"move": 1,
		"battle": 1,
		"patriot": 'British',
		"prize": 'Russian',
		"number": 23
	},
	{
		"name": "Ranjit Singh",
		"region": 'Punjab',
		"suit": 'Political',
		"rank": 2,
		"armies": 1,
		"tribes": 2,
		"betray": 1,
		"number": 24
	},
	{
		"name": "Josiah Harlan",
		"region": 'Punjab',
		"suit": 'Political',
		"rank": 1,
		"tribes": 1,
		"tax": 1,
		"patriot": 'Afghan',
		"prize": 'British',
		"number": 25
	},
	{
		"name": "Paolo Avitabile",
		"region": 'Punjab',
		"suit": 'Political',
		"rank": 1,
		"armies": 1,
		"tribes": 1,
		"betray": 1,
		"prize": 'Afghan',
		"number": 26
	},
	{
		"name": "Maqpon Dynasty",
		"region": 'Punjab',
		"suit": 'Political',
		"rank": 1,
		"tribes": 1,
		"leveraged": 1,
		"build": 1,
		"number": 27
	},
	{
		"name": "Anarkali Bazaar",
		"region": 'Punjab',
		"suit": 'Economic',
		"rank": 1,
		"roads": 1,
		"spies": 1,
		"tax": 1,
		"build": 1,
		"prize": 'Afghan',
		"number": 28
	},
	{
		"name": "Khyber Pass",
		"region": 'Punjab',
		"suit": 'Economic',
		"rank": 2,
		"roads": 2,
		"tax": 2,
		"move": 2,
		"number": 29
	},
	{
		"name": "Sikh Merchants in Lahore",
		"region": 'Punjab',
		"suit": 'Economic',
		"rank": 1,
		"roads": 1,
		"spies": 1,
		"leveraged": 1,
		"tax": 1,
		"gift": 1,
		"number": 30
	},
	{
		"name": "Company Weapons",
		"region": 'Punjab',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"climate": 'Intelligence',
		"tax": 1,
		"betray": 1,
		"number": 31
	},
	{
		"name": "Army of the Indus",
		"region": 'Punjab',
		"suit": 'Military',
		"rank": 3,
		"armies": 3,
		"move": 3,
		"patriot": 'British',
		"prize": 'Afghan',
		"number": 32
	},
	{
		"name": "Zorawar Singh Kahluria",
		"region": 'Punjab',
		"suit": 'Military',
		"rank": 2,
		"armies": 2,
		"gift": 1,
		"battle": 2,
		"number": 33
	},
	{
		"name": "Sindhi Warriors",
		"region": 'Punjab',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"climate": 'Economic',
		"move": 1,
		"battle": 1,
		"betray": 1,
		"prize": 'British',
		"number": 34
	},
	{
		"name": "Hari Singh Nalwa",
		"region": 'Punjab',
		"suit": 'Military',
		"rank": 2,
		"armies": 2,
		"climate": 'Political',
		"move": 2,
		"battle": 2,
		"number": 35
	},
	{
		"name": "Bengal Native Infantry",
		"region": 'Punjab',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"climate": 'Intelligence',
		"battle": 1,
		"betray": 1,
		"patriot": 'British',
		"prize": 'Afghan',
		"number": 36
	},
	{
		"name": "Seaforth Highlanders",
		"region": 'Punjab',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"climate": 'Political',
		"move": 1,
		"battle": 1,
		"patriot": 'British',
		"prize": 'Afghan',
		"number": 37
	},
	{
		"name": "Akali Sikhs",
		"region": 'Punjab',
		"suit": 'Military',
		"rank": 2,
		"armies": 2,
		"battle": 2,
		"prize": 'British',
		"number": 38
	},
	{
		"name": "William Moorcroft",
		"region": 'Kandahar',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"move": 1,
		"battle": 1,
		"number": 39
	},
	{
		"name": "William Hay Macnaghten",
		"region": 'Kandahar',
		"suit": 'Intelligence',
		"rank": 2,
		"spies": 2,
		"leveraged": 1,
		"tax": 2,
		"move": 2,
		"patriot": 'British',
		"prize": 'Afghan',
		"number": 40
	},
	{
		"name": "Charles Masson",
		"region": 'Kandahar',
		"suit": 'Intelligence',
		"rank": 2,
		"spies": 2,
		"build": 1,
		"number": 41
	},
	{
		"name": "Barakzai Sadars",
		"region": 'Kandahar',
		"suit": 'Political',
		"rank": 1,
		"tribes": 1,
		"leveraged": 1,
		"climate": 'Economic',
		"build": 1,
		"patriot": 'Afghan',
		"prize": 'Afghan',
		"number": 42
	},
	{
		"name": "Giljee Nobles",
		"region": 'Kandahar',
		"suit": 'Political',
		"rank": 1,
		"armies": 1,
		"tribes": 1,
		"battle": 1,
		"prize": 'Afghan',
		"number": 43
	},
	{
		"name": "Baluchi Chiefs",
		"region": 'Kandahar',
		"suit": 'Political',
		"rank": 1,
		"armies": 1,
		"tribes": 1,
		"tax": 1,
		"build": 1,
		"prize": 'Russian',
		"number": 44
	},
	{
		"name": "Haji Khan Kakar",
		"region": 'Kandahar',
		"suit": 'Political',
		"rank": 1,
		"armies": 1,
		"tribes": 1,
		"gift": 1,
		"betray": 1,
		"number": 45
	},
	{
		"name": "Bank",
		"region": 'Kandahar',
		"suit": 'Economic',
		"rank": 2,
		"roads": 2,
		"leveraged": 1,
		"climate": 'Intelligence',
		"gift": 1,
		"number": 46
	},
	{
		"name": "Bolan Pass",
		"region": 'Kandahar',
		"suit": 'Economic',
		"rank": 2,
		"armies": 1,
		"roads": 2,
		"gift": 1,
		"move": 2,
		"prize": 'Russian',
		"number": 47
	},
	{
		"name": "Fruit Markets",
		"region": 'Kandahar',
		"suit": 'Economic',
		"rank": 1,
		"roads": 1,
		"climate": 'Political',
		"build": 1,
		"move": 1,
		"number": 48
	},
	{
		"name": "Kandahari Markets",
		"region": 'Kandahar',
		"suit": 'Economic',
		"rank": 1,
		"roads": 1,
		"climate": 'Political',
		"tax": 1,
		"build": 1,
		"number": 49
	},
	{
		"name": "British Regulars",
		"region": 'Kandahar',
		"suit": 'Military',
		"rank": 2,
		"armies": 2,
		"move": 2,
		"battle": 2,
		"patriot": 'British',
		"prize": 'Russian',
		"number": 50
	},
	{
		"name": "Sir John Keane",
		"region": 'Kandahar',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"battle": 1,
		"patriot": 'British',
		"prize": 'Russian',
		"number": 51
	},
	{
		"name": "Pashtun Mercenary",
		"region": 'Kandahar',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"climate": 'Political',
		"tax": 1,
		"battle": 1,
		"number": 52
	},
	{
		"name": "Jezail Sharpshooters",
		"region": 'Kandahar',
		"suit": 'Military',
		"rank": 2,
		"armies": 2,
		"spies": 1,
		"betray": 1,
		"prize": 'Russian',
		"number": 53
	},
	{
		"name": "Herati Bandits",
		"region": 'Herat',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"leveraged": 1,
		"tax": 1,
		"number": 54
	},
	{
		"name": "Hazara Chiefs",
		"region": 'Herat',
		"suit": 'Political',
		"rank": 1,
		"armies": 1,
		"tribes": 1,
		"tax": 1,
		"move": 1,
		"battle": 1,
		"number": 55
	},
	{
		"name": "Yar Mohammad Alikozai",
		"region": 'Herat',
		"suit": 'Political',
		"rank": 2,
		"tribes": 2,
		"climate": 'Political',
		"betray": 1,
		"prize": 'Afghan',
		"number": 56
	},
	{
		"name": "Exiled Durrani Nobility",
		"region": 'Herat',
		"suit": 'Political',
		"rank": 1,
		"tribes": 1,
		"move": 1,
		"betray": 1,
		"prize": 'British',
		"number": 57
	},
	{
		"name": "Ishaqzai Chiefs",
		"region": 'Herat',
		"suit": 'Political',
		"rank": 1,
		"tribes": 1,
		"climate": 'Economic',
		"gift": 1,
		"build": 1,
		"patriot": 'Afghan',
		"number": 58
	},
	{
		"name": "Tajik Warband",
		"region": 'Herat',
		"suit": 'Military',
		"rank": 2,
		"armies": 2,
		"battle": 2,
		"betray": 1,
		"number": 59
	},
	{
		"name": "Nomadic Warlord",
		"region": 'Herat',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"tax": 1,
		"gift": 1,
		"battle": 1,
		"prize": 'Russian',
		"number": 60
	},
	{
		"name": "Karakul Sheep",
		"region": 'Herat',
		"suit": 'Economic',
		"rank": 2,
		"roads": 2,
		"tax": 2,
		"number": 61
	},
	{
		"name": "Qanat System",
		"region": 'Herat',
		"suit": 'Economic',
		"rank": 1,
		"roads": 1,
		"climate": 'Political',
		"gift": 1,
		"build": 1,
		"number": 62
	},
	{
		"name": "Farah Road",
		"region": 'Herat',
		"suit": 'Economic',
		"rank": 3,
		"roads": 3,
		"move": 3,
		"number": 63
	},
	{
		"name": "Opium Fields",
		"region": 'Herat',
		"suit": 'Economic',
		"rank": 2,
		"roads": 2,
		"spies": 1,
		"climate": 'Military',
		"tax": 2,
		"number": 64
	},
	{
		"name": "Minaret of Jam",
		"region": 'Herat',
		"suit": 'Economic',
		"rank": 1,
		"armies": 1,
		"roads": 1,
		"tax": 1,
		"move": 1,
		"battle": 1,
		"number": 65
	},
	{
		"name": "Baluchi Smugglers",
		"region": 'Herat',
		"suit": 'Economic',
		"rank": 2,
		"armies": 1,
		"roads": 2,
		"battle": 2,
		"prize": 'Afghan',
		"number": 66
	},
	{
		"name": "Wheat Fields",
		"region": 'Herat',
		"suit": 'Economic',
		"rank": 2,
		"roads": 1,
		"gift": 1,
		"move": 2,
		"number": 67
	},
	{
		"name": "Ghaem Magham Farahani",
		"region": 'Persia',
		"suit": 'Intelligence',
		"rank": 2,
		"armies": 1,
		"spies": 2,
		"tax": 2,
		"number": 68
	},
	{
		"name": "Count Ivan Simonich",
		"region": 'Persia',
		"suit": 'Intelligence',
		"rank": 2,
		"spies": 2,
		"move": 2,
		"battle": 2,
		"patriot": 'Russian',
		"prize": 'British',
		"number": 69
	},
	{
		"name": "Alexander Griboyedov",
		"region": 'Persia',
		"suit": 'Intelligence',
		"rank": 2,
		"spies": 2,
		"move": 2,
		"patriot": 'Russian',
		"prize": 'Afghan',
		"number": 70
	},
	{
		"name": "Joseph Wolff",
		"region": 'Persia',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"gift": 1,
		"move": 1,
		"patriot": 'British',
		"prize": 'Afghan',
		"number": 71
	},
	{
		"name": "Claude Wade",
		"region": 'Persia',
		"suit": 'Intelligence',
		"rank": 2,
		"spies": 2,
		"move": 2,
		"prize": 'Russian',
		"number": 72
	},
	{
		"name": "Jean-François Allard",
		"region": 'Persia',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"climate": 'Military',
		"build": 1,
		"battle": 1,
		"prize": 'British',
		"number": 73
	},
	{
		"name": "Hajj Mirza Aghasi",
		"region": 'Persia',
		"suit": 'Political',
		"rank": 1,
		"tribes": 1,
		"climate": 'Intelligence',
		"battle": 1,
		"betray": 1,
		"patriot": 'Afghan',
		"prize": 'Russian',
		"number": 74
	},
	{
		"name": "Abbas Mirza",
		"region": 'Persia',
		"suit": 'Political',
		"rank": 1,
		"armies": 1,
		"tribes": 1,
		"tax": 1,
		"battle": 1,
		"number": 75
	},
	{
		"name": "Fath-Ali Shah",
		"region": 'Persia',
		"suit": 'Political',
		"rank": 2,
		"tribes": 2,
		"climate": 'Intelligence',
		"number": 76
	},
	{
		"name": "Mohammad Shah",
		"region": 'Persia',
		"suit": 'Political',
		"rank": 1,
		"armies": 1,
		"tribes": 1,
		"climate": 'Intelligence',
		"build": 1,
		"betray": 1,
		"number": 77
	},
	{
		"name": "Civic Improvements",
		"region": 'Persia',
		"suit": 'Economic',
		"rank": 2,
		"roads": 2,
		"leveraged": 1,
		"climate": 'Intelligence',
		"build": 1,
		"number": 78
	},
	{
		"name": "Persian Slave Markets",
		"region": 'Persia',
		"suit": 'Economic',
		"rank": 1,
		"roads": 1,
		"spies": 1,
		"leveraged": 1,
		"tax": 1,
		"move": 1,
		"prize": 'British',
		"number": 79
	},
	{
		"name": "Anglo-Persian Trade",
		"region": 'Persia',
		"suit": 'Economic',
		"rank": 1,
		"roads": 1,
		"leveraged": 1,
		"tax": 1,
		"build": 1,
		"patriot": 'British',
		"prize": 'Russian',
		"number": 80
	},
	{
		"name": "Russo-Persian Trade",
		"region": 'Persia',
		"suit": 'Economic',
		"rank": 2,
		"roads": 2,
		"leveraged": 1,
		"tax": 2,
		"build": 1,
		"patriot": 'Russian',
		"prize": 'British',
		"number": 81
	},
	{
		"name": "Persian Army",
		"region": 'Persia',
		"suit": 'Military',
		"rank": 2,
		"armies": 2,
		"climate": 'Intelligence',
		"gift": 1,
		"battle": 2,
		"number": 82
	},
	{
		"name": "Shah's Guard",
		"region": 'Persia',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"spies": 1,
		"tax": 1,
		"number": 83
	},
	{
		"name": "Russian Regulars",
		"region": 'Persia',
		"suit": 'Military',
		"rank": 2,
		"armies": 2,
		"climate": 'Economic',
		"battle": 2,
		"patriot": 'Russian',
		"prize": 'Afghan',
		"number": 84
	},
	{
		"name": "Bukharan Jews",
		"region": 'Transcaspia',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"leveraged": 1,
		"climate": 'Economic',
		"gift": 1,
		"build": 1,
		"prize": 'British',
		"number": 85
	},
	{
		"name": "Jan Prosper Witkiewicz",
		"region": 'Transcaspia',
		"suit": 'Intelligence',
		"rank": 2,
		"spies": 2,
		"build": 1,
		"move": 2,
		"patriot": 'Russian',
		"number": 86
	},
	{
		"name": "Imperial Surveyors",
		"region": 'Transcaspia',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"gift": 1,
		"build": 1,
		"move": 1,
		"patriot": 'Russian',
		"number": 87
	},
	{
		"name": "Arthur Conolly",
		"region": 'Transcaspia',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"gift": 1,
		"move": 1,
		"patriot": 'British',
		"number": 88
	},
	{
		"name": "Aga Mehdi",
		"region": 'Transcaspia',
		"suit": 'Intelligence',
		"rank": 1,
		"spies": 1,
		"move": 1,
		"battle": 1,
		"betray": 1,
		"patriot": 'Russian',
		"number": 89
	},
	{
		"name": "Nasrullah Khan",
		"region": 'Transcaspia',
		"suit": 'Political',
		"rank": 1,
		"tribes": 1,
		"tax": 1,
		"betray": 1,
		"prize": 'British',
		"number": 90
	},
	{
		"name": "Allah Quli Bahadur",
		"region": 'Transcaspia',
		"suit": 'Political',
		"rank": 1,
		"armies": 1,
		"tribes": 1,
		"spies": 1,
		"betray": 1,
		"prize": 'Russian',
		"number": 91
	},
	{
		"name": "Mir Murad Beg",
		"region": 'Transcaspia',
		"suit": 'Political',
		"rank": 1,
		"tribes": 1,
		"spies": 1,
		"climate": 'Military',
		"tax": 1,
		"move": 1,
		"battle": 1,
		"prize": 'British',
		"number": 92
	},
	{
		"name": "Madali Khan",
		"region": 'Transcaspia',
		"suit": 'Political',
		"rank": 2,
		"tribes": 2,
		"battle": 2,
		"betray": 1,
		"prize": 'British',
		"number": 93
	},
	{
		"name": "Khivan Slave Markets",
		"region": 'Transcaspia',
		"suit": 'Economic',
		"rank": 1,
		"roads": 1,
		"spies": 1,
		"leveraged": 1,
		"tax": 1,
		"betray": 1,
		"prize": 'British',
		"number": 94
	},
	{
		"name": "Supplies from Orenburg",
		"region": 'Transcaspia',
		"suit": 'Economic',
		"rank": 1,
		"roads": 1,
		"tax": 1,
		"move": 1,
		"patriot": 'Russian',
		"prize": 'Afghan',
		"number": 95
	},
	{
		"name": "Panjdeh Oasis",
		"region": 'Transcaspia',
		"suit": 'Economic',
		"rank": 2,
		"roads": 2,
		"tax": 2,
		"move": 2,
		"prize": 'British',
		"number": 96
	},
	{
		"name": "Ark of Bukhara",
		"region": 'Transcaspia',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"climate": 'Intelligence',
		"build": 1,
		"number": 97
	},
	{
		"name": "European Cannons",
		"region": 'Transcaspia',
		"suit": 'Military',
		"rank": 3,
		"armies": 3,
		"gift": 1,
		"prize": 'British',
		"number": 98
	},
	{
		"name": "Cossacks",
		"region": 'Transcaspia',
		"suit": 'Military',
		"rank": 1,
		"armies": 1,
		"spies": 1,
		"battle": 1,
		"patriot": 'Russian',
		"prize": 'British',
		"number": 99
	},
	{
		"name": "Count Perovsky",
		"region": 'Transcaspia',
		"suit": 'Military',
		"rank": 2,
		"armies": 2,
		"battle": 2,
		"patriot": 'Russian',
		"prize": 'British',
		"number": 100
	},

	{
		"name": "Dominance Check",
		"if_discarded": "Dominance Check",
		"if_purchased": "Dominance Check",
		"number": 101,
	},
	{
		"name": "Dominance Check",
		"if_discarded": "Dominance Check",
		"if_purchased": "Dominance Check",
		"number": 102,
	},
	{
		"name": "Dominance Check",
		"if_discarded": "Dominance Check",
		"if_purchased": "Dominance Check",
		"number": 103,
	},
	{
		"name": "Dominance Check",
		"if_discarded": "Dominance Check",
		"if_purchased": "Dominance Check",
		"number": 104,
	},

	{
		"name": "EVENT",
		"if_discarded": "Military",
		"if_purchased": "New Tactics",
		"number": 105,
	},

	{
		"name": "EVENT",
		"if_discarded": "Embarrassment of Riches",
		"if_purchased": "Koh-i-noor Recovered",
		"number": 106,
	},

	{
		"name": "EVENT",
		"if_discarded": "Disregard for Customs",
		"if_purchased": "Courtly Manners",
		"number": 107,
	},

	{
		"name": "EVENT",
		"if_discarded": "Failure to Impress",
		"if_purchased": "Rumor",
		"number": 108,
	},

	{
		"name": "EVENT",
		"if_discarded": "Riots in Punjab",
		"if_purchased": "Conflict Fatigue",
		"number": 109,
	},

	{
		"name": "EVENT",
		"if_discarded": "Riots in Herat",
		"if_purchased": "Nationalism",
		"number": 110,
	},

	{
		"name": "EVENT",
		"if_discarded": "No effect",
		"if_purchased": "Public Withdrawal",
		"number": 111,
	},

	{
		"name": "EVENT",
		"if_discarded": "Riots in Kabul",
		"if_purchased": "Nation Building",
		"number": 112,
	},

	{
		"name": "EVENT",
		"if_discarded": "Riots in Persia",
		"if_purchased": "Backing of Persian Aristocracy",
		"number": 113,
	},

	{
		"name": "EVENT",
		"if_discarded": "Confidence Failure",
		"if_purchased": "Other Persuasive Methods",
		"number": 114,
	},

	{
		"name": "EVENT",
		"if_discarded": "Intelligence",
		"if_purchased": "Pashtunwali Values",
		"number": 115,
	},

	{
		"name": "EVENT",
		"if_discarded": "Political",
		"if_purchased": "Rebuke",
		"number": 116,
	}
];

if (typeof module !== 'undefined')
	module.exports = cards;
